version: '3'
services:
  app:
    container_name: app
    build:
      context: ./images/api
    ports:
      - "8080:3000"
    env_file:
      - .env
    environment:
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test
      POSTGRES_DB: Test
      POSTGRES_HOST: db 
    volumes:
      - ./images/apiTest/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "prepare"]
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test
      POSTGRES_DB: Test
    volumes:
      - ./_volumes/db-dataTest:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB "]
      interval: 5s
      timeout: 5s
      retries: 10

    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - '5050:80'

volumes:
  db-data:
  pgadmin-data: