version: '3'
services:
  api:
    container_name: api
    build:
      context: ./images/api
    ports:
      - "8080:3000"
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      POSTGRES_HOST: db 
    volumes:
      - ./images/api/src:/usr/app/src
    depends_on:
      db:
        condition: service_healthy
    command: ["npm", "run", "ci"]
    
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB "]
      interval: 5s
      timeout: 5s
      retries: 10

    

volumes:
  db-data:
  pgadmin-data: